### ISSUE TITLE
DLLInject Failed

### ISSUE THREAD

**Issue by Nekomimis** [Wimberton/OriginPalia#1]
I'm no smart IT guy and I tried to search up the error on Google just incase it's on my end, but I still wasn't able to find any answers. I got hit with;
![bkhOzp2](https://github.com/Wimberton/OriginPalia/assets/99659295/2094062c-471a-433d-8b04-6b20747f6fcc)

Currently using CE as an injector.

**Comment by Wimberton** [comment]
That sounds like an issue with your installation of Cheat Engine.
Try using something like ExtremeInjector, GuidedHacking Injector, etc.

I will provide my loader with the next release.

**Comment by Mishur1** [comment]
Hey, running in the same error with three different Injectors.

![image](https://github.com/Wimberton/OriginPalia/assets/169717736/8db57113-af9f-4d57-ab2c-0b3bf9040a87)

Tried Steam and standalone Client - Which Injector do you use? How do you inject the game?

**Comment by eduardneghina** [comment]
Same errors with CE & ExtremeInjector. Steam and standalone Client

**Comment by Wimberton** [comment]
> Same errors with CE & ExtremeInjector. Steam and standalone Client

Please try using a different injection method. It seems that this is an issue with your injector and the method being used, not the DLL itself. Nevertheless, please try the latest edition.

**Comment by Nekomimis** [comment]
Still no solution. Tried multiple different injectors. Rest went into Injection NULL. Hmm

**Comment by Nekomimis** [comment]
> > Still no solution. Tried multiple different injectors. Rest went into Injection NULL. Hmm
> 
> Like i said above, its not an injector issue, and the DLL works. The methods that the injectors are trying to use may not be available in your computer for example. I haven't done an indepth if that is the cause, what I may end up doing is completely uninstall everything i installed to get it to work on my other machine, and try to find out for you guys what it is.

My bad. Completely skipped through the replies. Do update us regarding the issue. I'm just lost because Balls' dll worked perfectly fine before.

**Comment by eduardneghina** [comment]
I Injected sucesfully after installing those 2 toolkits (w11 & MSVC v142 ) and I can see in the top "Origin Palia 0.179.1" but how do I open the menu ?!

**Comment by Nekomimis** [comment]
Thanks @VoidPollo , I got it to run now. I'm planning on closing the thread unless you need to continue your research?
So far the only issues I have is;

- Assertion Failure, the one where you have the same issue with. But for now, I kept spamming, "Ignore" until it disappears.
- I think being in the, "Selling & Items" menu, makes me experience the, "Game Travel Failure" error. Might just be me tho.

That's about it.

**Comment by Wimberton** [comment]
> @Wimberton
> 
> In the CMakeLists.txt
> 
> I changed:
> 
> `add_compile_options(/MP)`
> 
> to
> 
> `add_compile_options(/MP /MD)`
> 
> and my second machine can now load the .dll without having to install visual studios and the dependencies, perhaps check out whats available? might benefit the project.

Looking into this now. Thanks for the heads up!

**Comment by Wimberton** [comment]
> Thanks @VoidPollo , I got it to run now. I'm planning on closing the thread unless you need to continue your research?
> 
> So far the only issues (in terms of errors) I have is;
> 
> * Assertion Failure, the one where you have the same issue with. But for now, I kept spamming, "Ignore" until it disappears.
> * I think being in the, "Selling & Items" menu, makes me experience the, "Game Travel Failure" error. Might just be me tho.
> 
> **Suggestions:** All in all, it's really an amazing menu. I have to give it credit. I wonder if it would be possible to increase the Silent Aim range? Instead of max 30m, it could be slightly further? Mainly because I prefer shooting from a longer range xD. Also being able to save certain coordinates (Not the default ones you get when entering Kilima/Bahari) so that we can just click to TP would be good too. Being able to save ESP Color settings
> 
> That's about it.
> 
> Edit: Added inputs & suggestions

1. Silent aim had a valid range between when the animal is in combat stage, or not. It's something I'm looking into more.
2. Saving and loading coordinates alongside ESP colors, and currently active options is something I'm also working on in the background. It's going to take a bit of rewriting and finishing my config structures to get this going. It's coming.

I'm going to close this issue since I've added multithreaded runtime support for common runtime components. Thanks again VoidPollo for this suggestion.
