### ISSUE TITLE
Failed to download the DLL.

### ISSUE THREAD

**Issue by fortunecafe5** [Wimberton/OriginPalia#11]
Welcome to the OriginPalia Injector!

Please choose an option:
1. Start Injection Process
2. Exit
1
Starting the injection process...
Searching for game processes...
Found process: PaliaClient-Win64-Shipping
Game process found: PaliaClient-Win64-Shipping. Preparing to inject DLL...
Failed to download the DLL.

**Comment by Wimberton** [comment]
I'll take a look at this tomorrow. In the meantime, injecting using another DLL injector should work.

**Comment by Wimberton** [comment]
> Welcome to the OriginPalia Injector!
> 
> Please choose an option:
> 
> 1. Start Injection Process
> 2. Exit
>    1
>    Starting the injection process...
>    Searching for game processes...
>    Found process: PaliaClient-Win64-Shipping
>    Game process found: PaliaClient-Win64-Shipping. Preparing to inject DLL...
>    Failed to download the DLL.

I've resolved the issue with failing to download the DLL from the KeyAuth servers.
You should be all set. I'll close this issue report with this message.
