### ISSUE TITLE
Teleport to Target tweak suggestion

### ISSUE THREAD

**Issue by VoidPollo** [Wimberton/OriginPalia#14]
1) I found myself fighting a lot with the terrain, I'd spawn inside the ground or weird things. Perhaps add a randomized offset to X Y either positive or negative by (not really sure in in-game metrics) like 1 character apart from the resource and also a little higher on the Z.

2) Perhaps an option called along the lines "Prevent teleporting to targeted with nearby players", that prevents you to teleport to targeted if a player is either: 

- Near you
- Near the targeted entity you're about to teleport to

and perhaps any type of controls to configure how far you'd like players to be before you teleport.

**Comment by Wimberton** [comment]
> 1 thing to keep in mind with randomized offset is that you will also have to check the location is valid, I think there was a method to check for that. For example, I was teleporting to Heat Roots which spawn on the side of cliffs, currently it works perfectly for those since I can't get stuck in the ground, I just grab the heat root as I fall, but if you added a randomized offset im not sure if the game would make the player hang to the mountain if its too close to it, or clip the player inside the cliff and fall through the map.

We already do this somewhat in the teleport to targeting system. I'll definitely take a look at reworking some of the offsetting, I've personally had no issues. 

That code is referenced here:
```c++
FVector TargetLocation = Overlay->BestTargetLocation;
FVector ActorLocation = PlayerPawn->K2_GetActorLocation();

// Calculate offset based on distance between actor and target
FVector Offset = (TargetLocation - ActorLocation).GetNormalized() * 100.0f;

FVector NewLocation = TargetLocation + Offset;
FHitResult HitResult;
HitResult.bBlockingHit = false;
PlayerPawn->K2_SetActorLocation(NewLocation, false, &HitResult, true);
Overlay->LastTeleportToTargetTime = now;
```

**Comment by Wimberton** [comment]
> ![chances](https://private-user-images.githubusercontent.com/5094754/330934334-eb78f1b6-a000-41bb-98de-967b2db96458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDE0NDIsIm5iZiI6MTcxNTgwMTE0MiwicGF0aCI6Ii81MDk0NzU0LzMzMDkzNDMzNC1lYjc4ZjFiNi1hMDAwLTQxYmItOThkZS05NjdiMmRiOTY0NTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMTkyNTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQxZjhjM2E3YzgwYTllMDA3MDVjNWZmN2IwZGU4MmE4ZDFhMzNlMzVjYzljZDc1YmI1Yjg0NGZjNjgxZTYwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.E_gXGbE45my_zIEXjNbEBf7YmmTHdKDWJM3BZMT1AVc) ![chance2](https://private-user-images.githubusercontent.com/5094754/330934632-1a0c4025-e61a-49c4-ba31-a46d293c6778.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDE0NDIsIm5iZiI6MTcxNTgwMTE0MiwicGF0aCI6Ii81MDk0NzU0LzMzMDkzNDYzMi0xYTBjNDAyNS1lNjFhLTQ5YzQtYmEzMS1hNDZkMjkzYzY3NzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMTkyNTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODI1MDFjMzE4NjA3ZDgwM2YxNzlhZDgzYmNjMTg0MzdkNzA1NmFmNGQ2OGIwYzhiNTUyNzlmYzBlMWUzODJlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pWibvn99fEldlMyuYCipiP8bGos8ppfDyqqf2zDsA1I)
> 
> I'd say its a 5~10% of this happening

Thanks for reporting this. I'll rework the teleportation offsets so hopefully this happens less.

**Comment by Wimberton** [comment]
> 1 thing to keep in mind with randomized offset is that you will also have to check the location is valid, I think there was a method to check for that. For example, I was teleporting to Heat Roots which spawn on the side of cliffs, currently it works perfectly for those since I can't get stuck in the ground, I just grab the heat root as I fall, but if you added a randomized offset im not sure if the game would make the player hang to the mountain if its too close to it, or clip the player inside the cliff and fall through the map.

I've pushed an update to this mechanic. Let me know if it helps at all. Or possibly give me some coordinates you're having issues at for me to go and debug in-game.

**Comment by Wimberton** [comment]
> So, while it still works, its very predictable when it will not.
> 
> In this example:
> 
> ![oh2](https://private-user-images.githubusercontent.com/5094754/330962531-3c58c0c0-c0ae-4f37-9a14-1535b3fa978a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MTYxMzQsIm5iZiI6MTcxNTgxNTgzNCwicGF0aCI6Ii81MDk0NzU0LzMzMDk2MjUzMS0zYzU4YzBjMC1jMGFlLTRmMzctOWExNC0xNTM1YjNmYTk3OGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMjMzMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDhiOWM3YTc2M2YyMTc0ODllZDNjMTI0MmFlOTdkYmU3YzY3OTgxMjFlOTI1NmVkYTA5ZjllY2VlYzlhZGZkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BcQhMn5Lhpyph9JJeoCtz8D6BZbL3_nI7cG7P_qOYXU)
> 
> Knowing my angle and the node, I know im getting stuck because while playing with it on my plot, I can predict this will happen:
> 
> ![1](https://private-user-images.githubusercontent.com/5094754/330962711-5f4ff7ba-ebf0-4539-9b3f-58375bc82d7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MTYxMzQsIm5iZiI6MTcxNTgxNTgzNCwicGF0aCI6Ii81MDk0NzU0LzMzMDk2MjcxMS01ZjRmZjdiYS1lYmYwLTQ1MzktOWIzZi01ODM3NWJjODJkN2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMjMzMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzVmYmQyMzEwOTM1NDBlZjc3MjEwZGNjM2M3YzYzMWQ5M2U5MmE0MGY3NmY3MDYzYjkzZDAyNmY5M2YzNjRiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7xH_qt3mMFPCQRnkUGX3WpfbMoiWzUsfnZi3kxx2qkk)
> 
> So surely when I did: ![oh1](https://private-user-images.githubusercontent.com/5094754/330962781-5bd9230a-ce0d-4f24-88a7-193bdd48543e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MTYxMzQsIm5iZiI6MTcxNTgxNTgzNCwicGF0aCI6Ii81MDk0NzU0LzMzMDk2Mjc4MS01YmQ5MjMwYS1jZTBkLTRmMjQtODhhNy0xOTNiZGQ0ODU0M2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMjMzMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFjYTBjYTA4OTZmMjRkMzI3ZTI1NjMxMzE2MmE2ZmJkZmQ4MWZkN2M2ZGE2OWExNjZiM2M0ZTgxZTc1OGMzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oFA5P4oL_kbfzVvIpe9_lkdPGmlZRMbOKbFGkQKsERA)
> 
> I wonder if theres a better way to detect "Air" or "Nothing" in a radius of that coordinate, and keep going around each angle until a "good" location is found, if no good location is found then just go for the best one it think it found.

I'll definitely look at moving the player slightly to check for spawn spaces. Not a bad idea. Now to figure out the right way to implement it.

**Comment by Wimberton** [comment]
> > > So, while it still works, its very predictable when it will not.
> > > In this example:
> > > ![oh2](https://private-user-images.githubusercontent.com/5094754/330962531-3c58c0c0-c0ae-4f37-9a14-1535b3fa978a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MTYxMzQsIm5iZiI6MTcxNTgxNTgzNCwicGF0aCI6Ii81MDk0NzU0LzMzMDk2MjUzMS0zYzU4YzBjMC1jMGFlLTRmMzctOWExNC0xNTM1YjNmYTk3OGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMjMzMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDhiOWM3YTc2M2YyMTc0ODllZDNjMTI0MmFlOTdkYmU3YzY3OTgxMjFlOTI1NmVkYTA5ZjllY2VlYzlhZGZkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BcQhMn5Lhpyph9JJeoCtz8D6BZbL3_nI7cG7P_qOYXU)
> > > Knowing my angle and the node, I know im getting stuck because while playing with it on my plot, I can predict this will happen:
> > > ![1](https://private-user-images.githubusercontent.com/5094754/330962711-5f4ff7ba-ebf0-4539-9b3f-58375bc82d7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MTYxMzQsIm5iZiI6MTcxNTgxNTgzNCwicGF0aCI6Ii81MDk0NzU0LzMzMDk2MjcxMS01ZjRmZjdiYS1lYmYwLTQ1MzktOWIzZi01ODM3NWJjODJkN2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMjMzMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzVmYmQyMzEwOTM1NDBlZjc3MjEwZGNjM2M3YzYzMWQ5M2U5MmE0MGY3NmY3MDYzYjkzZDAyNmY5M2YzNjRiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7xH_qt3mMFPCQRnkUGX3WpfbMoiWzUsfnZi3kxx2qkk)
> > > So surely when I did: ![oh1](https://private-user-images.githubusercontent.com/5094754/330962781-5bd9230a-ce0d-4f24-88a7-193bdd48543e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MTYxMzQsIm5iZiI6MTcxNTgxNTgzNCwicGF0aCI6Ii81MDk0NzU0LzMzMDk2Mjc4MS01YmQ5MjMwYS1jZTBkLTRmMjQtODhhNy0xOTNiZGQ0ODU0M2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMjMzMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFjYTBjYTA4OTZmMjRkMzI3ZTI1NjMxMzE2MmE2ZmJkZmQ4MWZkN2M2ZGE2OWExNjZiM2M0ZTgxZTc1OGMzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oFA5P4oL_kbfzVvIpe9_lkdPGmlZRMbOKbFGkQKsERA)
> > > I wonder if theres a better way to detect "Air" or "Nothing" in a radius of that coordinate, and keep going around each angle until a "good" location is found, if no good location is found then just go for the best one it think it found.
> > 
> > 
> > I'll definitely look at moving the player slightly to check for spawn spaces. Not a bad idea. Now to figure out the right way to implement it. I also noticed that the ESP ores show even after the node being mined. I'll look into adding a checkbox to display mined nodes or not.
> 
> Don't add a checkbox, it should be automatic.
> 
> Trees Disappear (Flow included) Heat Roots disappear I think everything else disappears.
> 
> I was always annoyed that when I mined the ores it didn't behave like everything else, all nodes despawn on their own after some time and spawn elsewhere in the world, so it makes no sense to keep them there if mined.
> 
> Edit:
> 
> Heat Roots ingame also behave like Ores in the sense that an invisible object is left behind after being taken. Unlike trees, they fully despawn. But the heat root's ESP does go away as it should.
> 
> ![heatroot](https://private-user-images.githubusercontent.com/5094754/331007371-117002c5-161d-4a24-9879-ba48137f8fa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzA0NTAsIm5iZiI6MTcxNTg3MDE1MCwicGF0aCI6Ii81MDk0NzU0LzMzMTAwNzM3MS0xMTcwMDJjNS0xNjFkLTRhMjQtOTg3OS1iYTQ4MTM3ZjhmYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMTQzNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWJjZjc3YTAwMWZjZTg3Y2I3ZDg3MzY0YzIxODUwOGU0MzFhZTI3MWI0NGNkMmE2M2Q2YjU5ODI1MDI0MTU3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CxC2OAyjkQnQeCtpC6H7E5DX62OzhzpRJ3BGz3DrYa8)
> 
> Edit 2: You see my stamina bar? would be nice to have it unlimited, its possible with CE, so.. maybe something that can be done?

Stamina can definitely be done through hooking the mechanic and forcing max stamina numbers. I'll look at that.
I'll also take a look at the Heat Root configuration and see what's different between ores and that.

**Comment by Wimberton** [comment]
I'm going to close this one while we have the other general movement teleportation issue report.
I won't forget the climbing stamina. Working on it now.
