### ISSUE TITLE
[High-Priority] [Bug] Fishing

### ISSUE THREAD

**Issue by VoidPollo** [Wimberton/OriginPalia#16]
Last commit, I didn't catch it in time.. but 

![fishingerror](https://github.com/Wimberton/OriginPalia/assets/5094754/f514fa08-74b3-4509-be88-f8ce7e75f285)

My whole inventory got discarded, 10 at the time in 2 slots, so 20x items per catch, I thought it was being sent to storage or something but nope. All gone.

Also, you cannot sell junk to the fishermen, i tried talking to the general store to see if it would trigger to sell junk, but nope, the junk stayed, and everything else got discarded.

**Comment by Wimberton** [comment]
I'll revert the junk and discard back to it's original form. Thanks for letting me know!

**Comment by Wimberton** [comment]
I've pushed a hotfix for this, reverting it back.

**Comment by Wimberton** [comment]
> Ok, simple note for the hotfix:
> 
> Discard Other Unsellables doesnt state (Slot 1) (for now) Also, it will still discard fish if the selling fails, perhaps do not discard type fish, if it failed once it will fail every time, if the user left it as afk without noticing doing this change will at least grant them a full inventory of fish and random chests when they come back, instead of empty.

I've updated the wording. Essentially if you want to sell fish, it won't work either way and I find it more annoying to quickly fill up. When I'm AFKing, I'm not looking for fish so rarely does that case happen for me.

**Comment by Wimberton** [comment]
> Ok, simple note for the hotfix:
> 
> Discard Other Unsellables doesnt state (Slot 1) (for now) Also, it will still discard fish if the selling fails, perhaps do not discard type fish, if it failed once it will fail every time, if the user left it as afk without noticing doing this change will at least grant them a full inventory of fish and random chests when they come back, instead of empty.

I've updated the wording. Essentially if you want to sell fish, it won't work either way and I find it more annoying to quickly fill up. When I'm AFKing, I'm not looking for fish so rarely does that case happen for me.
