### ISSUE TITLE
Game crash when hover over gamespeed

### ISSUE THREAD

**Issue by dzsiki** [Wimberton/OriginPalia#2]
Every time my mouse go over the game speed slider the game frezze and than crash after a while.

**Comment by Wimberton** [comment]
Thank you for notifying me. Can you possibly attach a screen recording of the issue?
I'm unable to receive that issue on my end.

**Comment by dzsiki** [comment]
Its just fine now... But i got it 3 times in a row. i will try to record it if its happen again

**Comment by Wimberton** [comment]
> Its just fine now... But i got it 3 times in a row. i will try to record it if its happen again
Thanks! I'll be on the lookout for that.
I've pushed an update that may or may not have an effect on this, let me know if you have it again.

**Comment by Wimberton** [comment]
> Its just fine now... But i got it 3 times in a row. i will try to record it if its happen again

Hey @dzsiki I'm going to close this issue this evening if things are working smoothly for you now.
Please give the latest V1.6 a try, it should work better, and for both Steam and Standalone clients.

**Comment by Wimberton** [comment]
I've closed this issue due to the lack of responses.
