### ISSUE TITLE
SDK Dump

### ISSUE THREAD

**Issue by 01010100010100100100100101000111** [Wimberton/OriginPalia#26]
To both; could you help on the dump steps? have a load to learn, if I can at least get a grip with getting the SDK dump, can try lend a hand... Spent a few hours trina figure but failing >_< right now seems be "if you know you know", can you help us? Asserts are not having it and not sure how to go (dumper-7)

**Comment by Wimberton** [comment]
You'll need to inject the Dumper DLL into the game then let it do it's thing. Sometimes it will crash. You have to find the sweet spot for your instance.

More about Dumper-7 [can be found here](https://github.com/Encryqed/Dumper-7)

**Comment by 01010100010100100100100101000111** [comment]
Done that, got the SDK output without errors, then try compile OriginP, and get a bunch of offset wrong assert errors >_< cany chance for a bit more detail on dumper-7 steps?

**Comment by Wimberton** [comment]
> Done that, got the SDK output without errors, then try compile OriginP, and get a bunch of offset wrong assert errors >_< any chance for a bit more detail on dumper-7 steps?
> 
> Edit: appreciate any help, if you have a donate link, please share :)

In the [README file within the PaliaSDK](https://github.com/Wimberton/OriginPalia/blob/main/PaliaSDK/README.txt), we have
`NOTE: Replace the Offsets from constexpr to inline for steam/standlone change support`

You'll need to go into your Basic.hpp and make sure your Offsets are `inline`, not `constexpr`.
If you're going to support the steam edition, you need to allow the Offsets to be able to mutate during initialization.

**Comment by 01010100010100100100100101000111** [comment]
Ok, thanks! Hopefully next time I can be more use!
