### ISSUE TITLE
Cant reopen cheat menu after closing it.

### ISSUE THREAD

**Issue by dzsiki** [Wimberton/OriginPalia#3]
For the first time i can open the menu with ins fine, but every other time after i opened it before its just a flash. Its open and close instantly after 1 frame.

**Comment by dzsiki** [comment]
Only when closeing it with the X. If i close it with Ins its just works fine

**Comment by Wimberton** [comment]
Thanks for notifying me.
I've noticed this happens depending on your graphical settings in-game. Can you check those out for me?
I'll take a look myself and see if I can replicate the issue.

**Comment by dzsiki** [comment]
https://youtu.be/I030lZZlxqM

**Comment by Wimberton** [comment]
> https://youtu.be/I030lZZlxqM

I've fixed this issue and am pushing a patch now, along with some other safechecks.

**Comment by Wimberton** [comment]
> https://youtu.be/I030lZZlxqM
I've fixed this issue and am pushing a patch now, along with some other safechecks.
