### ISSUE TITLE
Discord Server invite link

### ISSUE THREAD

**Issue by noorabdo2** [Wimberton/OriginPalia#31]
Hi, i tried to join the discord server through the invite link 'yS9uWFedBA' but isn't working

**Comment by noorabdo2** [comment]
![image](https://github.com/Wimberton/OriginPalia/assets/43034992/16ee1913-12c4-4b26-804e-bf2330c33d11)

**Comment by Wimberton** [comment]
> ![image](https://private-user-images.githubusercontent.com/43034992/331912056-16ee1913-12c4-4b26-804e-bf2330c33d11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNjg5NjksIm5iZiI6MTcxNjE2ODY2OSwicGF0aCI6Ii80MzAzNDk5Mi8zMzE5MTIwNTYtMTZlZTE5MTMtMTJjNC00YjI2LTgwNGUtYmYyMzMwYzMzZDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDAxMzEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYWRmN2EzNGE2MTQ2OTdjMWMyMjk0N2ViMTg1OWE5ZjZhYTc3YjU1YjhmZDJhZWU0MGNiMzYyOGM0OTQyNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h99894Gd8yr6rSo7MdkIGUj72At9HjAVj31qgxs5qDA)

Hmm, the Discord invite link is still valid. I'll look into this.
[click me to join](https://discord.com/invite/yS9uWFedBA)

**Comment by Wimberton** [comment]
Closing this since that link works on my end. I'm not sure what else I can do.
