### ISSUE TITLE
teleport dropped loot to player

### ISSUE THREAD

**Issue by ivantehassassin** [Wimberton/OriginPalia#32]
this feature when i toggle on sometimes works and sometimes it doesnt

**Comment by recso** [comment]
yup, same here
Also Placing decoration doesn't work for me now

**Comment by ivantehassassin** [comment]
placing decoration works fine u just have to plave the item first in ur plot and then just move where u wanna place it

**Comment by Wimberton** [comment]
> this feature when i toggle on sometimes works and sometimes it doesnt

You must have LOOT ESP enabled for it to work. I'm going to change that in a few patches.

**Comment by Wimberton** [comment]
> yup, same here Also Placing decoration doesn't work for me now

Placing house decorations works in your plot. You'll need to enable it and then move your items. You can place successfully in red-outlined zones. If it stopped working, try enabling and disabling it again.

**Comment by ivantehassassin** [comment]
> > this feature when i toggle on sometimes works and sometimes it doesnt
> 
> You must have LOOT ESP enabled for it to work. I'm going to change that in a few patches.

Loot esp?

**Comment by ivantehassassin** [comment]
Also the target animal orbit how it works?

**Comment by Wimberton** [comment]
> Also the target animal orbit how it works?

I'm going to remove this feature until I finish it. It was originally a personal one for fun, just makes animals orbit you with a really funny custom algorithm for distances, like planets.

Nowhere near done. I have to remove the animal AI brain component before it's functional.

**Comment by Wimberton** [comment]
Closing this issue report with the message above.
