### ISSUE TITLE
Suggestions for Gameplay speed

### ISSUE THREAD

**Issue by noorabdo2** [Wimberton/OriginPalia#33]
if possible can we change the gameplay speed by ourself ? not limited to a specific options like half or 50 , 75 , 100 ?
i used the ctrl + left click to change it by myself and i got crash
because i use the speed gameplay 100 to fish + cheat engine to increase it a bit more.

and also a option like a 'black screen', 'remove lag' will be appreciated. 
that option was in cheat i used before which make the screen all black only game-menu UI there

**Comment by noorabdo2** [comment]
Wimberton replayed in discord that it will be min-max and choice is to us so i will close this issue 
![image](https://github.com/Wimberton/OriginPalia/assets/43034992/9beada17-cad8-4ec5-a4e9-8400c5e9ff94)

**Comment by Wimberton** [comment]
> if possible can we change the gameplay speed by ourself ? not limited to a specific options like half or 50 , 75 , 100 ? i used the ctrl + left click to change it by myself and i got crash because i use the speed gameplay 100 to fish + cheat engine to increase it a bit more.
> 
> and also a option like a 'black screen', 'remove lag' will be appreciated. that option was in cheat i used before which make the screen all black only game-menu UI there

Doing something like a minimal render view would be interesting. It would stop some rendering issues when speeding up the game faster than allowed. I'll definitely take a look into that route! Thanks for the suggestion!
