### ISSUE TITLE
Latest version issues

### ISSUE THREAD

**Issue by Instant2155** [Wimberton/OriginPalia#37]
I downloaded the 0.180 version from github.

-Legacy aim is not working.

-Pickup judgment does not teleport.
Only the appearance of the dropped item will be teleported above the player's head.

For example, if you shoot a deer from a distance, the dropped item will appear to teleport away, but the actual pick-up detection will occur near the deer carcass.

-crash

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000262

PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
OHook
OHook
OHook
OHook
OHook
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
PaliaClient_Win64_Shipping
kernel32
ntdll

**Comment by Wimberton** [comment]
I'll be working on this first-thing when I get back into town from my emergency family surgery travels. Thanks for your patience with me, @Instant2155.
