### ISSUE TITLE
[Question] Fast Fishing

### ISSUE THREAD

**Issue by BunkaH** [Wimberton/OriginPalia#46]
So.. i tried the new .dll and is working fine, even the toggle to capture fishing pool, but i've been using this .dll with my own CE Table for fast fishing and noticed that the new .dll fast fishing is slower than the one i've been using with my table, even using it at x15 global speed (mine was a lot faster and looks like the dll fast fishing wont even get any benefit from time dilation)
So i though and tried to ask if is possible to make the "fast fishing" a toggle instead of default so i can use my own table instead of using the dll fast fishing by default? .-.

Thanks for keeping the great work, really appreciate it!

Kinda new using github and my english sucks, sorry c,c

**Comment by BunkaH** [comment]
v2.5.1 Fast Fishing is awesome, is much faster now, i couldnt managed to vanish the bobble with CE only(yet) (i've managed to use it with other scripts from my table, so is even faster than before now, but after some tests i noticed that even with x15 global speed, it wont affect the fishing speed anymore due to how quick it is fishing now, the server limits how fast it can be, maybe?, But who cares about limit, is much faster than it was before with just my table and auto fish+global speed)

Thanks so much for the great work, you guys rocks!

(i'm closing the issue, thanks for taking your time and make it, i really really appreciatte this, for taking considerations for just comments that you could just ignore!)

**Comment by BunkaH** [comment]
> I believe there is a server limit as to how fast we can ping? But if its able to be bypassed you know we'll eventually try it :) I'm glad its working better now ^^

Tried many things with CE only and compiled a version without the bobber speed and cast range to compare with default versions, i think i found what makes it "limit" the fishing speed, servers seems to check the distance btween player and cast range(i'm not sure, but thats the only thing i can think that's limiting the fishing right now), so i compiled it again with reduced fishing cast range and it was faster, reeling speed seems to make no/little effect at all(need more tests to make sure). So, is it possible to make the cast range configurable? ( i've it on my CE script, but since the DLL overwrite it to max, it has no effect when enabled c,c )

(Just commenting, the actual fishing works great, thanks for your time!)

**Comment by Wimberton** [comment]
> > I believe there is a server limit as to how fast we can ping? But if its able to be bypassed you know we'll eventually try it :) I'm glad its working better now ^^
> 
> Tried many things with CE only and compiled a version without the bobber speed and cast range to compare with default versions, i think i found what makes it "limit" the fishing speed, servers seems to check the distance btween player and cast range(i'm not sure, but thats the only thing i can think that's limiting the fishing right now), so i compiled it again with reduced fishing cast range and it was faster, reeling speed seems to make no/little effect at all(need more tests to make sure). So, is it possible to make the cast range configurable? ( i've it on my CE script, but since the DLL overwrite it to max, it has no effect when enabled c,c )
> 
> (edit 1: also tried to disable reeling animations, makes the fishing even faster with lower cast range) (edit 2: yeah, i've tested even more the cast range + bobber range from player, and noticed that when i zero it, i can catch almost 8~10 fishes per sec and global speed wont even affect it anymore(bobber was crazy, like 50 times per sec), i can think there's something similar to what happens when we remove animations for fast mining/cutting, server checks how fast it can be and limit it, i dont think if there's a way to bypass it)
> 
> (Just commenting, the actual fishing works great, thanks for your time!)

I'll take some of this into consideration with the next patches!
