### ISSUE TITLE
originpalia/dll: ESP 'Enable all' selection no longer showing with 2.4

### ISSUE THREAD

**Issue by EmptyVisual** [Wimberton/OriginPalia#49]
The 'Enable all' selection within ESP settings is no longer present as of 2.4.

Screenshots for reference:

**Current Version 2.4-hotfix**
![image](https://github.com/Wimberton/OriginPalia/assets/4710051/2b307eff-7079-4740-b57b-b54898ae6f61)

Version 2.3
![image](https://github.com/Wimberton/OriginPalia/assets/4710051/904ab23e-561a-44f2-bb06-70db9c826060)

**Environment**
Affected DLL Version: V2.4_HOTFIX
Last known working: V.2.3
Game Version: Steam / 0.180.0

**Comment by Wimberton** [comment]
Ill add them back now. Thanks for the recommendation!
