### ISSUE TITLE
Ready dll

### ISSUE THREAD

**Issue by bibimashina** [Wimberton/OriginPalia#5]
Can someone send already ready dll for injection into the game? I just don't understand what I need to do to play with it.

**Comment by Wimberton** [comment]
The ready DLL is provided in the release! You can use any DLL injector to play with it.

**Comment by bibimashina** [comment]
> The ready DLL is provided in the release! You can use any DLL injector to play with it.

Where is it located? I can't find it in your files

**Comment by Nekomimis** [comment]
> > The ready DLL is provided in the release! You can use any DLL injector to play with it.
> 
> Where is it located? I can't find it in your files

On the right side, there should be a section called, “Releases”, you can download it from there.

**Comment by Wimberton** [comment]
> bibimashina

You can find the latest DLL posted [in the releases section](https://github.com/Wimberton/OriginPalia/releases).
I will keep this DLL updated each time I rebuild and push new code. Feel free to check back for new versions often, especially during the beginning releases of this.
