### ISSUE TITLE
Empty Menu (Steam version)

### ISSUE THREAD

**Issue by recso** [Wimberton/OriginPalia#6]
tried injecting -> injected successfuly -> Press Insert -> Pops up the menu with all 6 tabs but each one of is empty

**Comment by Wimberton** [comment]
The menu will be empty in lobbies, you will need to be in-game for the menu to populate.
I've disabled menu options in places other than in-game so you don't crash.

**Comment by Tintir** [comment]
I think he is talking about a problem with Steam version, there is such a problem there.

**Comment by recso** [comment]
> The menu will be empty in lobbies, you will need to be in-game for the menu to populate. I've disabled menu options in places other than in-game so you don't crash.

I have steam version,
I also have Cmake and visual studio installed with the required dependencies
![Untitled3](https://github.com/Wimberton/OriginPalia/assets/29873376/a4ae089c-a9dc-4966-bf80-e241f8e59195)

**Comment by recso** [comment]
> The menu will be empty in lobbies, you will need to be in-game for the menu to populate. I've disabled menu options in places other than in-game so you don't crash.

I have steam version,
I also have Cmake and visual studio installed with the required dependencies
![Untitled3](https://github.com/Wimberton/OriginPalia/assets/29873376/722e3aab-491c-49cd-b191-69dc886b2ea9)

**Comment by recso** [comment]
also when trying the loader :
![image](https://github.com/Wimberton/OriginPalia/assets/29873376/c31b7136-8bf7-43a2-8c28-22b92def4db6)

**Comment by recso** [comment]
> I don't use it on the steam version, but ill leave this for Wim:
> 
> ```
> DWORD WINAPI MainThread(LPVOID lpReserved)
> {
> 	bool IsSteamVersion = false;
> 	if ((uintptr_t)GetModuleHandle("steam_api64.dll")) {
> 		IsSteamVersion = true;
> 	}
> 	else if ((uintptr_t)GetModuleHandle("steamclient64.dll")) {
> 		IsSteamVersion = true;
> 	}
> 	else {
> 		char fileName[MAX_PATH];
> 		GetModuleFileName(NULL, fileName, MAX_PATH);
> 		if (strstr(fileName, "PaliaClientSteam-Win64-Shipping.exe")) {
> 			IsSteamVersion = true;
> 		}
> 	}
> 	if (IsSteamVersion) {
> 		SDK::Offsets::GObjects     = 0x089C9C00;
> 		SDK::Offsets::AppendString = 0x00CF9A50;
> 		SDK::Offsets::GWorld       = 0x08B3A638;
> 		SDK::Offsets::ProcessEvent = 0x00ED35D0;
> 	}
> 	SDK::InitGObjects();
> 	auto Overlay = new PaliaOverlay();
> 	OverlayBase::Instance = Overlay;
> 	Overlay->SetupColors();
> 	Overlay->SetupUserConfig();
> 	Overlay->SetupOverlay();
> 	return TRUE;
> }
> ```

sorry didn't catch, using steam version i think its not compatible no?

**Comment by Wimberton** [comment]
> > > I don't use it on the steam version, but ill leave this for Wim:
> > > ```
> > > DWORD WINAPI MainThread(LPVOID lpReserved)
> > > {
> > > 	bool IsSteamVersion = false;
> > > 	if ((uintptr_t)GetModuleHandle("steam_api64.dll")) {
> > > 		IsSteamVersion = true;
> > > 	}
> > > 	else if ((uintptr_t)GetModuleHandle("steamclient64.dll")) {
> > > 		IsSteamVersion = true;
> > > 	}
> > > 	else {
> > > 		char fileName[MAX_PATH];
> > > 		GetModuleFileName(NULL, fileName, MAX_PATH);
> > > 		if (strstr(fileName, "PaliaClientSteam-Win64-Shipping.exe")) {
> > > 			IsSteamVersion = true;
> > > 		}
> > > 	}
> > > 	if (IsSteamVersion) {
> > > 		SDK::Offsets::GObjects     = 0x089C9C00;
> > > 		SDK::Offsets::AppendString = 0x00CF9A50;
> > > 		SDK::Offsets::GWorld       = 0x08B3A638;
> > > 		SDK::Offsets::ProcessEvent = 0x00ED35D0;
> > > 	}
> > > 	SDK::InitGObjects();
> > > 	auto Overlay = new PaliaOverlay();
> > > 	OverlayBase::Instance = Overlay;
> > > 	Overlay->SetupColors();
> > > 	Overlay->SetupUserConfig();
> > > 	Overlay->SetupOverlay();
> > > 	return TRUE;
> > > }
> > > ```
> > 
> > 
> > sorry didn't catch, using steam version i think its not compatible no?
> 
> It can be, this project is a revamped version of the previous one I was using, it did work for steam as well but it needed that code above.

I will implement this and give it a go. Thanks for sharing!

**Comment by Wimberton** [comment]
> also when trying the loader : ![image](https://private-user-images.githubusercontent.com/29873376/330556366-c31b7136-8bf7-43a2-8c28-22b92def4db6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTM1NTUsIm5iZiI6MTcxNTcxMzI1NSwicGF0aCI6Ii8yOTg3MzM3Ni8zMzA1NTYzNjYtYzMxYjcxMzYtOGJmNy00M2EyLThjMjgtMjJiOTJkZWY0ZGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE5MDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NDlmYmNiMTk3NzM0OTZjNjZmMTk0Y2I4MWQ1ZTMxYzVjNTIyOWJlYjIzZmIxODQyMDNlODYzMmI0ODg2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LLrr14BRk6ezSS7NHywVxPAkgcmYQEYs_w6mYscfWu8)

My loader is having issues with license auth. I use this loader for a lot of things. Let me fix the loader and re-upload it.

**Comment by Wimberton** [comment]
> > I don't use it on the steam version, but ill leave this for Wim:
> > ```
> > DWORD WINAPI MainThread(LPVOID lpReserved)
> > {
> > 	bool IsSteamVersion = false;
> > 	if ((uintptr_t)GetModuleHandle("steam_api64.dll")) {
> > 		IsSteamVersion = true;
> > 	}
> > 	else if ((uintptr_t)GetModuleHandle("steamclient64.dll")) {
> > 		IsSteamVersion = true;
> > 	}
> > 	else {
> > 		char fileName[MAX_PATH];
> > 		GetModuleFileName(NULL, fileName, MAX_PATH);
> > 		if (strstr(fileName, "PaliaClientSteam-Win64-Shipping.exe")) {
> > 			IsSteamVersion = true;
> > 		}
> > 	}
> > 	if (IsSteamVersion) {
> > 		SDK::Offsets::GObjects     = 0x089C9C00;
> > 		SDK::Offsets::AppendString = 0x00CF9A50;
> > 		SDK::Offsets::GWorld       = 0x08B3A638;
> > 		SDK::Offsets::ProcessEvent = 0x00ED35D0;
> > 	}
> > 	SDK::InitGObjects();
> > 	auto Overlay = new PaliaOverlay();
> > 	OverlayBase::Instance = Overlay;
> > 	Overlay->SetupColors();
> > 	Overlay->SetupUserConfig();
> > 	Overlay->SetupOverlay();
> > 	return TRUE;
> > }
> > ```
> 
> sorry didn't catch, using steam version i think its not compatible no?

I've added in the SteamAPI code support. Please give it a try and let me know your results.
I will close this issue once confirmed.

**Comment by recso** [comment]
> > > I don't use it on the steam version, but ill leave this for Wim:
> > > ```
> > > DWORD WINAPI MainThread(LPVOID lpReserved)
> > > {
> > > 	bool IsSteamVersion = false;
> > > 	if ((uintptr_t)GetModuleHandle("steam_api64.dll")) {
> > > 		IsSteamVersion = true;
> > > 	}
> > > 	else if ((uintptr_t)GetModuleHandle("steamclient64.dll")) {
> > > 		IsSteamVersion = true;
> > > 	}
> > > 	else {
> > > 		char fileName[MAX_PATH];
> > > 		GetModuleFileName(NULL, fileName, MAX_PATH);
> > > 		if (strstr(fileName, "PaliaClientSteam-Win64-Shipping.exe")) {
> > > 			IsSteamVersion = true;
> > > 		}
> > > 	}
> > > 	if (IsSteamVersion) {
> > > 		SDK::Offsets::GObjects     = 0x089C9C00;
> > > 		SDK::Offsets::AppendString = 0x00CF9A50;
> > > 		SDK::Offsets::GWorld       = 0x08B3A638;
> > > 		SDK::Offsets::ProcessEvent = 0x00ED35D0;
> > > 	}
> > > 	SDK::InitGObjects();
> > > 	auto Overlay = new PaliaOverlay();
> > > 	OverlayBase::Instance = Overlay;
> > > 	Overlay->SetupColors();
> > > 	Overlay->SetupUserConfig();
> > > 	Overlay->SetupOverlay();
> > > 	return TRUE;
> > > }
> > > ```
> > 
> > 
> > sorry didn't catch, using steam version i think its not compatible no?
> 
> I've added in the SteamAPI code support. Please give it a try and let me know your results. I will close this issue once confirmed.

![image](https://github.com/Wimberton/OriginPalia/assets/29873376/0d31f993-a0e5-4b3b-b187-02b2a9bef466)
Same problem here tried the version 1.5 (im injecting with CE and Extreme injector), i will try switching to DX11 and let you know

![image](https://github.com/Wimberton/OriginPalia/assets/29873376/af68096e-52f4-4d96-8e56-f05dcd7186e2)
Also have the loader with access you removed

**Comment by firebirdjsb** [comment]
i can confirm blank menu as well newest dll using my own injector

**Comment by Wimberton** [comment]
> i can confirm blank menu as well newest dll using my own injector

You're referring to STEAM, or standalone client?
Are you in-game, or not?

**Comment by Wimberton** [comment]
> Errmm?? @Wimberton I think this got fixed after you added the /MD to the compile... I haven't changed anything, redownloaded sources with the changes youve added, recompiled and its working fine on steam..

That's really great to hear! Thank you for all of your contributions during this!
It's really great to have others helping out with the project. Especially with errors.

I don't use the Steam edition, but I'll start downloading it and see what I can find as well.
If you can provide a screenshot or something, I'll close this issue and confirm it working <3

**Comment by firebirdjsb** [comment]
my steam version is not working on 1.5.2

**Comment by Wimberton** [comment]
> Yeah.. 1.5.2 is not working, but my compiled version without any edits is working... ?? I'll upload it for the time being for the people in steam, but im not understanding whats breaking it..
> 
> https://mega.nz/file/MKZx0aLS#v3N0U-Il58vD2CtjvBJxK0a7G6UeooMCpjnsT14Fzck

That really is confusing. I'll do some quick review and see where that went wrong. I haven't made any changes that would reflect differently than earlier for Steam.

**Comment by firebirdjsb** [comment]
main difference i just tested  from void to the main one when i inject at the main menu it says it waits until loading then it shows the free version text in game and visuals work

**Comment by recso** [comment]
v1.5.1 - v1.5.2 =ESP and Aimbot tabs are showing now but the functions seems not working and the other tabs are still blank...
but Void's version is working for the moment, this is the first time it works for me... i'll keep testing

**Comment by Wimberton** [comment]
> @Wimberton I don't know if it has to do with MY PaliaSDK? I've been messing with both versions that im not even sure which SDK I got it dumpped from.

Sure, can you share the Offsets namespace for your `Basic.hpp`?
It will look something like this.

```
namespace Offsets
{
	constexpr int32 GObjects = 0x0895D980;
	constexpr int32 AppendString = 0x00CF9080;
	constexpr int32 GNames = 0x00000000;
	constexpr int32 GWorld = 0x08ACE3B8;
	constexpr int32 ProcessEvent = 0x00ED2AB0;
	constexpr int32 ProcessEventIdx = 0x0000004D;
}
```

**Comment by Wimberton** [comment]
> > > @Wimberton I don't know if it has to do with MY PaliaSDK? I've been messing with both versions that im not even sure which SDK I got it dumpped from.
> > 
> > 
> > Sure, can you share the Offsets namespace for your `Basic.hpp`? It will look something like this.
> > ```
> > namespace Offsets
> > {
> > 	constexpr int32 GObjects = 0x0895D980;
> > 	constexpr int32 AppendString = 0x00CF9080;
> > 	constexpr int32 GNames = 0x00000000;
> > 	constexpr int32 GWorld = 0x08ACE3B8;
> > 	constexpr int32 ProcessEvent = 0x00ED2AB0;
> > 	constexpr int32 ProcessEventIdx = 0x0000004D;
> > }
> > ```
> 
> Already one step ahead, I already had compared these earlier.
> 
> ```
> namespace Offsets
> {
> 	inline int32 GObjects        = 0x0895D980;
> 	inline int32 AppendString    = 0x00CF9080;
> 	inline int32 GNames          = 0x00000000;
> 	inline int32 GWorld          = 0x08ACE3B8;
> 	inline int32 ProcessEvent    = 0x00ED2AB0;
> 	inline int32 ProcessEventIdx = 0x0000004D;
> }
> ```
> 
> They were the same. So I'm assuming these are the dumps from the standalone. So idk why me compiling from my computer allows others to use it on steam, but not from yours?

I'm sure it has to do with the type instruction.
a constant expression is handled much differently than static, or even inline.
Thanks for sharing! I may have this figured out.

**Comment by Wimberton** [comment]
I can confirm the inline expression allows for mutation. Those pointers need to be immediately available, alongside being swapped.

A constexpr cannot be changed. This has been fixed and I'm pushing the update now.

**Comment by Wimberton** [comment]
I can confirm the inline expression allows for mutation. Those pointers need to be immediately available, alongside being swapped. A constexpr cannot be changed. **This has been fixed and I'm pushing the update now.**
