### ISSUE TITLE
Unable to use Auto hunt, swing, and catch

### ISSUE THREAD

**Issue by ajones073090** [Wimberton/OriginPalia#67]
I am unable to use auto hunt, catch, and swing. the show up red in the menu and state they are unavailable with this version of OriginPalia. How do I correct this? 
![IMG_3758](https://github.com/user-attachments/assets/0bb13850-2f02-4f35-b652-e8a0a377b771)

**Comment by Wimberton** [comment]
This functionality is not contained within our source-code and requires a key from our website.
The public repository contains majority of the features for free!

**Comment by ajones073090** [comment]
Hello,
If available what do I need to do get a key code?

Warmly,
Amber R. Jones
***@***.***



Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that. Hate multiplies hate, violence multiplies violence, and toughness multiplies toughness in a descending spiral of destruction....The chain reaction of evil--hate begetting hate, wars producing more wars--must be broken, or we shall be plunged into the dark abyss of annihilation.
-- Martin Luther King, Jr., The Strength To Love, 1963

**Comment by ajones073090** [comment]
Hello,

I purchased a key from your website, and nothing popped up for me to enter the license key. I tried redeeming it on the website, but it stated that it was either invalid or had already been used. I tried injecting it into the game like I did the other one and it still does not give me the option for the key. Can you please help?



Warmly,
Amber R. Jones
***@***.***



Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that. Hate multiplies hate, violence multiplies violence, and toughness multiplies toughness in a descending spiral of destruction....The chain reaction of evil--hate begetting hate, wars producing more wars--must be broken, or we shall be plunged into the dark abyss of annihilation.
-- Martin Luther King, Jr., The Strength To Love, 1963

**Comment by Wimberton** [comment]
> Hello, I purchased a key from your website, and nothing popped up for me to enter the license key. I tried redeeming it on the website, but it stated that it was either invalid or had already been used. I tried injecting it into the game like I did the other one and it still does not give me the option for the key. Can you please help? Warmly, Amber R. Jones ***@***.*** Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that. Hate multiplies hate, violence multiplies violence, and toughness multiplies toughness in a descending spiral of destruction....The chain reaction of evil--hate begetting hate, wars producing more wars--must be broken, or we shall be plunged into the dark abyss of annihilation. -- Martin Luther King, Jr., The Strength To Love, 1963
> […](#)
> On Sep 7, 2024 at 11:55 AM -0500, Wimberton ***@***.***>, wrote: This functionality is not contained within our source-code and requires a key from our website. The public repository contains majority of the features for free! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Hello @ajones073090,
If you're looking for support, this is not the right place.
Please either open a report ticket on our website, or send us a message via Discord. We'll help you as quickly as possible.
