### ISSUE TITLE
Microsoft Visual C++ Runtime Libary

### ISSUE THREAD

**Issue by fortunecafe5** [Wimberton/OriginPalia#9]
![image](https://github.com/Wimberton/OriginPalia/assets/38452252/86ae287e-da2b-4e64-94bb-87fb6e9b2a3a)

**Comment by Wimberton** [comment]
I'm looking into this now. I've not seen this from anyone else or on my end. When exactly are you having this error?

**Comment by fortunecafe5** [comment]
atm right now

**Comment by fortunecafe5** [comment]
If I am in the img GUI for a while then this message appears.

**Comment by fortunecafe5** [comment]
![image](https://github.com/Wimberton/OriginPalia/assets/38452252/c183184f-9df0-4f53-b1f1-0522fb87e84a)
Again, when I open the menu and want to set something, this window appears. The game is then freezed and is then closed after a while with a sendlog

**Comment by Wimberton** [comment]
> ![image](https://private-user-images.githubusercontent.com/38452252/330571244-c183184f-9df0-4f53-b1f1-0522fb87e84a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTYwNzAsIm5iZiI6MTcxNTcxNTc3MCwicGF0aCI6Ii8zODQ1MjI1Mi8zMzA1NzEyNDQtYzE4MzE4NGYtOWRmMC00ZjUzLWIxZjEtMDUyMmZiODdlODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE5NDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZTczZjU1NTA3NWIwNmY2ZjIyMzcyNzM3ZWYyZGQ0MjhjMGNkZDMxOWY2MmJhMGY3Y2JjYWYzYWUwOTA4MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-riUXLr2_Q9Zec-RHhlNcq_hox3cf1exvFITgcNcX70) Again, when I open the menu and want to set something, this window appears. The game is then freezed and is then closed after a while with a sendlog

When exactly are you opening the menu? At what part of the game process

**Comment by fortunecafe5** [comment]
I go directly into the game Rein when I am in the game, for example at a lake and then I turned on Instant fishing and then I just pressed esp and the message appears

**Comment by Wimberton** [comment]
> I can make it happen consistently
> 
> Open game -> Inject -> login -> Insert -> Enable legacy aimbot, Enable silent -> Disable both now -> Go to ESP and enable a few ESP entities (maybe that are near you?)
> 
> ![2222](https://private-user-images.githubusercontent.com/5094754/330572915-0fe9b68d-8154-43db-b584-eb8cce90ce6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTc3NTksIm5iZiI6MTcxNTcxNzQ1OSwicGF0aCI6Ii81MDk0NzU0LzMzMDU3MjkxNS0wZmU5YjY4ZC04MTU0LTQzZGItYjU4NC1lYjhjY2U5MGNlNmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMjAxMDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzA2NDAxMGMxZWU4OGNkMmEwMDBmNjQ5N2E4ODI2ZTA3MjMzMDNmMTNhOTk5ZDg0NDQyMzY5NjIxMzUyNzFhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HSQhy_qtJclHMrTmJPSAI8-BtGcJGF8nr2GhF4o7wmw)

I'm unable to make this erorr occur on my end.
Going into the game (whether it's doing this at the lobby, or in-game does not make a difference)
Enabling both Aimbot / Silent aim (disabling and enabling a few times)
Enabling and disabling ESP and it's options

I receive no issues with this. I've cleaned up some code, so hopefully this was somewhat resolved.
I'm currently working on a revision of how objects are called in the tabs, thanks for your patience.

**Comment by Wimberton** [comment]
> I think 1.5.1 fixed it for me? Still ~abusing~ testing it

Keep me informed. I'm installing the Steam edition now so I can work on both the standalone and Steam edition where it's needed.

**Comment by Wimberton** [comment]
> ![image](https://private-user-images.githubusercontent.com/38452252/330561622-86ae287e-da2b-4e64-94bb-87fb6e9b2a3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MjIxOTEsIm5iZiI6MTcxNTcyMTg5MSwicGF0aCI6Ii8zODQ1MjI1Mi8zMzA1NjE2MjItODZhZTI4N2UtZGEyYi00ZTY0LTk0YmItODdmYjZlOWIyYTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDIxMjQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MTM3NzNlYjMwZDVlNWQyNzYxNzk4MTVlZDUwN2E5YzhiYTFlNWZiNzFiNzZjNjUzY2QyZmE3NzRkMzVhNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S8TYds5ybS6D5roOEr1j18WgXzCk8Li5EM94AnPjI8Y)

Have you given the latest release DLL a try? I'd love to hear your results.

**Comment by Wimberton** [comment]
> Nevermind, same error happened again using the latest version... Nothing different, its just random when it happens. But I believe its only when the overlay is showing.
> 
> Im stumped.

What exactly happened? You enabled some ESP features, then toggled some aiming features, and it crashes?

**Comment by Wimberton** [comment]
> [ocornut/imgui#5769](https://github.com/ocornut/imgui/issues/5769)
> 
> Some interesting stuff there, not entirely sure if it applies here.

Very interesting. I'll look into updating the ImGui edition to the latest. It's a few behind, I've been lazy in that realm of things.

**Comment by Wimberton** [comment]
> The second machine that this error was happening a lot as well to hasn't happened once as well. I think this might be fixed

I'll go ahead and close this issue report until it happens again. Thanks for semi-confirming! I'm hoping the general recoding has been helping here and there.
